# Generated by Django 5.1.2 on 2024-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_recipe_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coocking_steps',
            new_name='cooking_steps',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='coocking_time',
            new_name='cooking_time',
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='category_photos/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_of_food',
            field=models.ImageField(upload_to='recipes_photos'),
        ),
    ]
